"""Self-Harness: a tiny auditable harness-improvement loop."""

from importlib.metadata import PackageNotFoundError, version

from self_harness.adapters.base import TaskAdapter
from self_harness.adapters.container_verifier import (
    ContainerCommandSpec,
    ContainerVerifierRunner,
    ContainerVerifierTaskAdapter,
    build_container_run_command,
)
from self_harness.adapters.http_verifier import HttpVerifierRunner, HttpVerifierTaskAdapter
from self_harness.adapters.in_process_python import (
    InProcessPythonRunner,
    InProcessPythonTaskAdapter,
    load_trusted_module,
)
from self_harness.adapters.llm import (
    GLM5_SPEC,
    MINIMAX_M25_SPEC,
    QWEN35_35B_A3B_SPEC,
    AnthropicClaudeClient,
    GLMClient,
    MiniMaxClient,
    OpenAICompatiblePaperModelClient,
    PaperModelBackendSpec,
    QwenClient,
)
from self_harness.adapters.verifier_result import VerifierResult
from self_harness.attestations import (
    AttestationCheck,
    AttestationError,
    AttestationTrustRoot,
    AttestationVerificationReport,
    PyPIAttestation,
    SigstoreBundle,
    SigstorePythonVerifier,
    StructuralAttestationVerifier,
    attestation_report_to_jsonable,
    load_attestation_trust_root,
    load_pypi_attestation,
    verify_attestation,
)
from self_harness.audit import (
    AuditRun,
    AuditSummary,
    audit_trajectory_rows,
    inspect_harness_run,
    load_audit_run,
    summarize_audit_run,
    write_audit_trajectory,
    write_harness_inspection,
)
from self_harness.audit_migration import (
    AuditMigrationError,
    AuditMigrationReport,
    audit_migration_report_to_jsonable,
    detect_audit_schema_version,
    migrate_audit_tree,
)
from self_harness.audit_verify import (
    AuditVerificationCheck,
    AuditVerificationReport,
    audit_verification_report_to_jsonable,
    verify_audit_run,
)
from self_harness.audit_verify_live import (
    LiveAuditProvenance,
    LiveAuditVerificationCheck,
    LiveAuditVerificationError,
    LiveAuditVerificationReport,
    live_audit_verification_report_to_jsonable,
    load_live_audit_provenance,
    verify_live_audit_run,
)
from self_harness.capture_admit import (
    CaptureAdmissionError,
    CaptureAdmissionResult,
    capture_admission_report_to_jsonable,
    run_capture_admission,
)
from self_harness.capture_extract import (
    CaptureExtractError,
    extract_artifact_from_paths,
    extract_container_image_trust_report,
    extract_fixed_protocol_config,
    extract_live_harbor_audit,
    extract_live_harbor_preflight_report,
    extract_live_terminal_bench_split_manifest,
    extract_live_two_repeat_evaluation_report,
    extract_model_backend_preflight_report,
    extract_network_resource_controls_attestation,
    extract_proposal_validation_manifest,
)
from self_harness.config import EngineConfig
from self_harness.corpus import (
    TaskCorpus,
    TaskLoadReason,
    corpus_checksum,
    corpus_integrity_payload,
    load_corpus,
    verify_corpus_signature,
)
from self_harness.corpus_keyring import (
    CorpusKeyring,
    KeyringEntry,
    KeyringStatus,
    add_keyring_entry,
    entries_for,
    load_keyring,
    save_keyring,
    set_keyring_entry_status,
    verify_corpus_with_keyring,
)
from self_harness.engine import SelfHarnessEngine
from self_harness.evaluation import Runner
from self_harness.exceptions import (
    AuditVerificationError,
    ContainerVerifierError,
    HttpVerifierError,
    InProcessVerifierError,
    KeyringError,
    LLMClientError,
    LLMRequestError,
)
from self_harness.harness import figure_3_harness, initial_harness
from self_harness.image_policy import (
    ImagePolicy,
    ImagePolicyDecision,
    ImagePolicyEntry,
    ImagePolicyError,
    ImagePolicyStatus,
    empty_image_policy,
    ensure_image_allowed,
    evaluate_image_policy,
    load_image_policy,
    validate_image_digest,
)
from self_harness.llm_proposer import LLMClient, LLMProposer
from self_harness.operator_bundle import (
    OperatorPolicyBundle,
    OperatorPolicyBundleError,
    load_operator_policy_bundle,
    operator_policy_bundle_to_jsonable,
)
from self_harness.operator_policy_binding import (
    PolicyBindingCheck,
    PolicyBindingReport,
    policy_binding_report_to_jsonable,
    verify_policy_binding,
)
from self_harness.operator_promotion import (
    PromotionCheck,
    PromotionEntry,
    PromotionError,
    PromotionManifest,
    PromotionSignature,
    PromotionVerificationReport,
    add_promotion_entry,
    init_promotion_manifest,
    load_promotion_manifest,
    promotion_manifest_to_jsonable,
    promotion_signature_to_jsonable,
    promotion_verification_report_to_jsonable,
    set_promotion_status,
    sign_promotion_manifest,
    verify_promotion_manifest,
    verify_promotion_signature,
)
from self_harness.proposer import Proposer
from self_harness.proposer_policy import ProposalPolicy
from self_harness.providers import (
    KmsSignature,
    OAuthToken,
    ProviderError,
    ProviderRegistry,
    RegistryCredential,
    SecretResolutionError,
    StaticKmsSigner,
    StaticOAuthTokenProvider,
    StaticRegistryCredentialProvider,
    StaticSecretResolver,
    provider_registry,
)
from self_harness.readiness import audit_tree_hash
from self_harness.readiness_drift import (
    ReadinessDriftCheck,
    ReadinessDriftError,
    ReadinessDriftReport,
    evaluate_readiness_drift,
    readiness_drift_report_to_jsonable,
)
from self_harness.readiness_matrix import (
    ReadinessMatrixCatalog,
    ReadinessMatrixEntry,
    ReadinessMatrixError,
    ReadinessMatrixReport,
    ReadinessMatrixRow,
    evaluate_readiness_matrix,
    load_readiness_matrix_catalog,
    readiness_matrix_report_to_jsonable,
)
from self_harness.reporting import build_benchmark_report, write_benchmark_report
from self_harness.signing import (
    ExternalSignerError,
    ExternalSignerFailure,
    ExternalSignerResponse,
    sign_corpus_with_external_signer,
)
from self_harness.testing import MockLLMClient

try:
    __version__ = version("self-harness")
except PackageNotFoundError:
    __version__ = "0.1.0"

__all__ = [
    "AuditRun",
    "AuditSummary",
    "AuditMigrationError",
    "AuditMigrationReport",
    "AnthropicClaudeClient",
    "GLM5_SPEC",
    "GLMClient",
    "AuditVerificationCheck",
    "AuditVerificationError",
    "AuditVerificationReport",
    "AttestationCheck",
    "AttestationError",
    "AttestationTrustRoot",
    "AttestationVerificationReport",
    "CaptureAdmissionError",
    "CaptureAdmissionResult",
    "CaptureExtractError",
    "ContainerCommandSpec",
    "ContainerVerifierError",
    "ContainerVerifierRunner",
    "ContainerVerifierTaskAdapter",
    "CorpusKeyring",
    "EngineConfig",
    "ExternalSignerError",
    "ExternalSignerFailure",
    "ExternalSignerResponse",
    "HttpVerifierError",
    "HttpVerifierRunner",
    "HttpVerifierTaskAdapter",
    "ImagePolicy",
    "ImagePolicyDecision",
    "ImagePolicyEntry",
    "ImagePolicyError",
    "ImagePolicyStatus",
    "InProcessPythonRunner",
    "InProcessPythonTaskAdapter",
    "InProcessVerifierError",
    "KeyringEntry",
    "KeyringError",
    "KeyringStatus",
    "KmsSignature",
    "LLMClientError",
    "LLMClient",
    "LLMProposer",
    "LLMRequestError",
    "LiveAuditProvenance",
    "LiveAuditVerificationCheck",
    "LiveAuditVerificationError",
    "LiveAuditVerificationReport",
    "MINIMAX_M25_SPEC",
    "MiniMaxClient",
    "MockLLMClient",
    "OAuthToken",
    "OpenAICompatiblePaperModelClient",
    "OperatorPolicyBundle",
    "OperatorPolicyBundleError",
    "PaperModelBackendSpec",
    "PolicyBindingCheck",
    "PolicyBindingReport",
    "PromotionCheck",
    "PromotionEntry",
    "PromotionError",
    "PromotionManifest",
    "PromotionSignature",
    "PromotionVerificationReport",
    "PyPIAttestation",
    "QWEN35_35B_A3B_SPEC",
    "QwenClient",
    "ProposalPolicy",
    "Proposer",
    "ProviderError",
    "ProviderRegistry",
    "ReadinessDriftCheck",
    "ReadinessDriftError",
    "ReadinessDriftReport",
    "ReadinessMatrixCatalog",
    "ReadinessMatrixEntry",
    "ReadinessMatrixError",
    "ReadinessMatrixReport",
    "ReadinessMatrixRow",
    "RegistryCredential",
    "Runner",
    "SecretResolutionError",
    "SelfHarnessEngine",
    "SigstoreBundle",
    "SigstorePythonVerifier",
    "StaticKmsSigner",
    "StaticOAuthTokenProvider",
    "StaticRegistryCredentialProvider",
    "StaticSecretResolver",
    "StructuralAttestationVerifier",
    "TaskAdapter",
    "TaskCorpus",
    "TaskLoadReason",
    "VerifierResult",
    "__version__",
    "add_keyring_entry",
    "add_promotion_entry",
    "audit_tree_hash",
    "audit_trajectory_rows",
    "audit_migration_report_to_jsonable",
    "attestation_report_to_jsonable",
    "audit_verification_report_to_jsonable",
    "build_benchmark_report",
    "build_container_run_command",
    "capture_admission_report_to_jsonable",
    "corpus_checksum",
    "corpus_integrity_payload",
    "empty_image_policy",
    "ensure_image_allowed",
    "entries_for",
    "evaluate_readiness_drift",
    "evaluate_readiness_matrix",
    "evaluate_image_policy",
    "extract_artifact_from_paths",
    "extract_container_image_trust_report",
    "extract_fixed_protocol_config",
    "extract_live_harbor_audit",
    "extract_live_harbor_preflight_report",
    "extract_live_terminal_bench_split_manifest",
    "extract_live_two_repeat_evaluation_report",
    "extract_model_backend_preflight_report",
    "extract_network_resource_controls_attestation",
    "extract_proposal_validation_manifest",
    "inspect_harness_run",
    "init_promotion_manifest",
    "initial_harness",
    "figure_3_harness",
    "load_audit_run",
    "load_attestation_trust_root",
    "load_corpus",
    "load_image_policy",
    "load_keyring",
    "load_live_audit_provenance",
    "load_operator_policy_bundle",
    "load_readiness_matrix_catalog",
    "load_promotion_manifest",
    "load_pypi_attestation",
    "load_trusted_module",
    "migrate_audit_tree",
    "operator_policy_bundle_to_jsonable",
    "policy_binding_report_to_jsonable",
    "promotion_manifest_to_jsonable",
    "promotion_signature_to_jsonable",
    "promotion_verification_report_to_jsonable",
    "provider_registry",
    "readiness_drift_report_to_jsonable",
    "readiness_matrix_report_to_jsonable",
    "live_audit_verification_report_to_jsonable",
    "run_capture_admission",
    "save_keyring",
    "set_keyring_entry_status",
    "set_promotion_status",
    "sign_corpus_with_external_signer",
    "sign_promotion_manifest",
    "summarize_audit_run",
    "validate_image_digest",
    "detect_audit_schema_version",
    "verify_audit_run",
    "verify_live_audit_run",
    "verify_attestation",
    "verify_corpus_with_keyring",
    "verify_corpus_signature",
    "verify_promotion_manifest",
    "verify_promotion_signature",
    "verify_policy_binding",
    "write_benchmark_report",
    "write_audit_trajectory",
    "write_harness_inspection",
]
